version: "3.9"

services:
  pg_zare_test:
    image: postgres:16.6
    container_name: pg_zare_test
    environment:
      POSTGRES_USER: usr_pg_zare_test
      POSTGRES_PASSWORD: pass_pg_zare_test
      POSTGRES_DB: db_pg_zare_test
    ports:
      - "9354:5432"
    volumes:
      - ./db_storage:/var/lib/postgresql/data

  adminer_zare_test:
    image: adminer:latest
    container_name: adminer_zare_test
    depends_on:
      - pg_zare_test
    environment:
      ADMINER_DEFAULT_SERVER: pg_zare_test
    ports:
      - "9388:8080"